name: 'General Translation'
description: 'Automatically translate your project with General Translation'
author: 'General Translation'
branding:
  icon: 'globe'
  color: 'blue'

inputs:
  node-version:
    description: 'Node.js version to use'
    default: '20'
    required: false
  working-directory:
    description: 'Directory where gt.config.json is located'
    default: '.'
    required: false
  api-key:
    description: 'General Translation API key'
    required: true
  project-id:
    description:
      'General Translation project ID (leave empty if provided in the
      gt.config.json file)'
    required: false
  commit-message:
    description: 'Commit message for translation updates'
    default: 'Update translations via General Translation API'
    required: false
  branch-name:
    description:
      'Branch name for translation updates (leave empty to commit directly to
      current branch)'
    required: false
  create-pull-request:
    description: 'Whether to create a pull request'
    default: 'false'
    required: false
  pull-request-title:
    description: 'Title for the pull request'
    default: 'Update translations'
    required: false
  pull-request-body:
    description: 'Body for the pull request'
    default: 'This PR updates translations via the General Translation API'
    required: false

outputs:
  pull-request-url:
    description: 'URL of the created pull request'
  pull-request-number:
    description: 'Number of the created pull request'

runs:
  using: 'node20'
  main: 'dist/index.js'
